### ISSUE TITLE
Paragraph alignment  not working after plugin installation

### ISSUE THREAD

**Issue by sdangol** [lubusIN/block-background#5]
If I install and activate the plugin, the alignment options for paragraphs donot work.

**Comment by ajitbohra** [comment]
looking into it

**Comment by sdangol** [comment]
@ajitbohra any progress on this?
It is not only affecting the paragraph alignment but also every other block element's attributes.

**Comment by ajitbohra** [comment]
@sdangol 

Tested with `WP 5.x` and its breaking all the blocks, fix will be released in the next few days.

Can you share a screenshot along with error details?

Would like to how you using Gutenberg as the plugin or with WordPress 5.0

**Comment by ajitbohra** [comment]
@sdangol we have released `v1.0.3` for `WordPress 5.0.2` compatibility.

let me know if latest update works.

**Comment by sdangol** [comment]
@ajitbohra 
I am using it in wordpress 5.0.2
The issue still persists.
Here are some screenshots.
<img width="2048" alt="screen shot 2019-01-04 at 11 45 52" src="https://user-images.githubusercontent.com/22979656/50675524-c6ac0d00-1016-11e9-9976-02bc5550a294.png">
<img width="2048" alt="screen shot 2019-01-04 at 11 46 40" src="https://user-images.githubusercontent.com/22979656/50675525-c6ac0d00-1016-11e9-8a22-ee946c1a94b4.png">

**Comment by ajitbohra** [comment]
@sdangol can you share the console log seems like some errors are logged

**Comment by ajitbohra** [comment]
@sdangol have released the fix in v1.0.4 can you confirm if that works for you.
